### ISSUE TITLE
Fully embrace TranscodingStreams

### ISSUE THREAD

**Issue by omus** [invenia/CodecLz4.jl#9]
Before we register this package we should:

- Rename the package to be "CodecLz4.jl" to fit in with the [rest of the codec packages](https://github.com/bicycle1885/TranscodingStreams.jl)
- Ensure that we're fully compliant with what TranscodingStreams.jl expects. We may want to get @bicycle1885's assistance here.

**Comment by bicycle1885** [comment]
Very nice work! I added this package to the list of codec packages: https://github.com/bicycle1885/TranscodingStreams.jl#codec-packages.

**Comment by morris25** [comment]
Thanks!
